
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Enroll;
import model.Postgraduate;


public class PostgraduateEvaluation extends javax.swing.JPanel {
    AdminPanel adminPanel;
    String Id;
    Postgraduate postg = new Postgraduate("","","","","","","","","","","");
    Enroll[] subjectsSem1 = new Enroll[8];
    Enroll[] selectedSubjectsSem1 = new Enroll[8];
    Enroll[] subjectsSem2 = new Enroll[8];
    Enroll[] selectedSubjectsSem2 = new Enroll[8];
    int countSem1=0,countSem2=0;
    /**
     * Creates new form PostgraduateEvaluation
     */
    public PostgraduateEvaluation(AdminPanel adminPanel) {
        this.adminPanel=adminPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStuId = new javax.swing.JLabel();
        jButtonStuId = new javax.swing.JButton();
        jTextStuId = new javax.swing.JTextField();
        jLabelCreditS13 = new javax.swing.JLabel();
        jLabelSem2 = new javax.swing.JLabel();
        jCheckBoxS13 = new javax.swing.JCheckBox();
        jCheckBoxS18 = new javax.swing.JCheckBox();
        jCheckBoxS14 = new javax.swing.JCheckBox();
        jCheckBoxS15 = new javax.swing.JCheckBox();
        jCheckBoxS16 = new javax.swing.JCheckBox();
        jCheckBoxS17 = new javax.swing.JCheckBox();
        jLabelCreditS16 = new javax.swing.JLabel();
        jLabelCreditS15 = new javax.swing.JLabel();
        jLabelCreditS14 = new javax.swing.JLabel();
        jLabelCreditS18 = new javax.swing.JLabel();
        jLabelCreditS17 = new javax.swing.JLabel();
        jLabelCreditS11 = new javax.swing.JLabel();
        jLabelCreditS12 = new javax.swing.JLabel();
        jButtonSubS11 = new javax.swing.JButton();
        jButtonSubS12 = new javax.swing.JButton();
        jLabelCashS11 = new javax.swing.JLabel();
        jButtonEditS1 = new javax.swing.JButton();
        jButtonProceedS1 = new javax.swing.JButton();
        jLabelCashS13 = new javax.swing.JLabel();
        jLabelCashS12 = new javax.swing.JLabel();
        jLabelCashS15 = new javax.swing.JLabel();
        jLabelCashS16 = new javax.swing.JLabel();
        jLabelCashS17 = new javax.swing.JLabel();
        jLabelCashS18 = new javax.swing.JLabel();
        jLabelCashS14 = new javax.swing.JLabel();
        jButtonSubS21 = new javax.swing.JButton();
        jButtonSubS22 = new javax.swing.JButton();
        jCheckBoxS23 = new javax.swing.JCheckBox();
        jCheckBoxS24 = new javax.swing.JCheckBox();
        jCheckBoxS25 = new javax.swing.JCheckBox();
        jCheckBoxS26 = new javax.swing.JCheckBox();
        jCheckBoxS27 = new javax.swing.JCheckBox();
        jCheckBoxS28 = new javax.swing.JCheckBox();
        jLabelCreditS21 = new javax.swing.JLabel();
        jLabelCreditS22 = new javax.swing.JLabel();
        jLabelCreditS23 = new javax.swing.JLabel();
        jLabelCreditS24 = new javax.swing.JLabel();
        jLabelCreditS25 = new javax.swing.JLabel();
        jLabelCreditS26 = new javax.swing.JLabel();
        jLabelCreditS27 = new javax.swing.JLabel();
        jLabelCreditS28 = new javax.swing.JLabel();
        jLabelCashS21 = new javax.swing.JLabel();
        jLabelCashS22 = new javax.swing.JLabel();
        jLabelCashS23 = new javax.swing.JLabel();
        jLabelCashS24 = new javax.swing.JLabel();
        jLabelCashS25 = new javax.swing.JLabel();
        jLabelCashS26 = new javax.swing.JLabel();
        jLabelCashS27 = new javax.swing.JLabel();
        jLabelCashS28 = new javax.swing.JLabel();
        jLabelSem1 = new javax.swing.JLabel();
        jButtonEditS2 = new javax.swing.JButton();
        jButtonProceedS2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStuId.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelStuId.setText("Student Id");
        add(jLabelStuId, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 80, 42));

        jButtonStuId.setText("Submit");
        jButtonStuId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStuIdActionPerformed(evt);
            }
        });
        add(jButtonStuId, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 96, 42));
        add(jTextStuId, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 110, 42));

        jLabelCreditS13.setText("3 Credits");
        add(jLabelCreditS13, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 379, 64, 30));

        jLabelSem2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSem2.setText("Semester 2");
        add(jLabelSem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 151, 141, 43));

        jCheckBoxS13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS13.setText("Database I");
        jCheckBoxS13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS13ActionPerformed(evt);
            }
        });
        add(jCheckBoxS13, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 373, 249, 43));

        jCheckBoxS18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS18.setText("Statistics I");
        jCheckBoxS18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS18ActionPerformed(evt);
            }
        });
        add(jCheckBoxS18, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 678, 249, 43));

        jCheckBoxS14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS14.setText("Computer Systems I");
        jCheckBoxS14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS14ActionPerformed(evt);
            }
        });
        add(jCheckBoxS14, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 434, 249, 43));

        jCheckBoxS15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS15.setText("Laboratory I");
        jCheckBoxS15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS15ActionPerformed(evt);
            }
        });
        add(jCheckBoxS15, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 495, 249, 43));

        jCheckBoxS16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS16.setText("Mathematical Methods I");
        jCheckBoxS16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS16ActionPerformed(evt);
            }
        });
        add(jCheckBoxS16, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 556, 249, 43));

        jCheckBoxS17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS17.setText("Computer Networks I");
        jCheckBoxS17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS17ActionPerformed(evt);
            }
        });
        add(jCheckBoxS17, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 617, 249, 43));

        jLabelCreditS16.setText("2 Credits");
        add(jLabelCreditS16, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 562, 64, 30));

        jLabelCreditS15.setText("2 Credits");
        add(jLabelCreditS15, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 501, 64, 30));

        jLabelCreditS14.setText("3 Credits");
        add(jLabelCreditS14, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 440, 64, 30));

        jLabelCreditS18.setText("2 Credits");
        add(jLabelCreditS18, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 684, 64, 30));

        jLabelCreditS17.setText("2 Credits");
        add(jLabelCreditS17, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 623, 64, 30));

        jLabelCreditS11.setText("3 Credits");
        add(jLabelCreditS11, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 259, 64, 30));

        jLabelCreditS12.setText("3 Credits");
        add(jLabelCreditS12, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 319, 64, 30));

        jButtonSubS11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonSubS11.setText("Data Structures and Algorithms I");
        add(jButtonSubS11, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 253, -1, 42));

        jButtonSubS12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonSubS12.setText("Programming I");
        add(jButtonSubS12, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 313, 249, 42));

        jLabelCashS11.setText("Rs 4500");
        add(jLabelCashS11, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 259, 59, 30));

        jButtonEditS1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonEditS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        jButtonEditS1.setText("Edit");
        add(jButtonEditS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 755, 148, 49));

        jButtonProceedS1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonProceedS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Proceed.png"))); // NOI18N
        jButtonProceedS1.setText("Proceed");
        jButtonProceedS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProceedS1ActionPerformed(evt);
            }
        });
        add(jButtonProceedS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 755, -1, 49));

        jLabelCashS13.setText("Rs 3500");
        add(jLabelCashS13, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 379, 59, 30));

        jLabelCashS12.setText("Rs 4500");
        add(jLabelCashS12, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 319, 59, 30));

        jLabelCashS15.setText("Rs 3000");
        add(jLabelCashS15, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 501, 59, 30));

        jLabelCashS16.setText("Rs 2500");
        add(jLabelCashS16, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 562, 59, 30));

        jLabelCashS17.setText("Rs 4500");
        add(jLabelCashS17, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 623, 59, 30));

        jLabelCashS18.setText("Rs 4000");
        add(jLabelCashS18, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 684, 59, 30));

        jLabelCashS14.setText("Rs 2500");
        add(jLabelCashS14, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 440, 59, 30));

        jButtonSubS21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonSubS21.setText("Data Structures and Algorithms II");
        add(jButtonSubS21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 253, -1, 42));

        jButtonSubS22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonSubS22.setText("Programming II");
        add(jButtonSubS22, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 313, 249, 42));

        jCheckBoxS23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS23.setText("Database II");
        jCheckBoxS23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS23ActionPerformed(evt);
            }
        });
        add(jCheckBoxS23, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 373, 249, 43));

        jCheckBoxS24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS24.setText("Computer Systems II");
        jCheckBoxS24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS24ActionPerformed(evt);
            }
        });
        add(jCheckBoxS24, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 434, 249, 43));

        jCheckBoxS25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS25.setText("Laboratory II");
        jCheckBoxS25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS25ActionPerformed(evt);
            }
        });
        add(jCheckBoxS25, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 495, 249, 43));

        jCheckBoxS26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS26.setText("Mathematical Methods II");
        jCheckBoxS26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS26ActionPerformed(evt);
            }
        });
        add(jCheckBoxS26, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 556, 249, 43));

        jCheckBoxS27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS27.setText("Computer Networks II");
        jCheckBoxS27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS27ActionPerformed(evt);
            }
        });
        add(jCheckBoxS27, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 617, 249, 43));

        jCheckBoxS28.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jCheckBoxS28.setText("Statistics II");
        jCheckBoxS28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxS28ActionPerformed(evt);
            }
        });
        add(jCheckBoxS28, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 678, 249, 43));

        jLabelCreditS21.setText("3 Credits");
        add(jLabelCreditS21, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 259, 64, 30));

        jLabelCreditS22.setText("3 Credits");
        add(jLabelCreditS22, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 319, 64, 30));

        jLabelCreditS23.setText("3 Credits");
        add(jLabelCreditS23, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 379, 64, 30));

        jLabelCreditS24.setText("3 Credits");
        add(jLabelCreditS24, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 440, 64, 30));

        jLabelCreditS25.setText("2 Credits");
        add(jLabelCreditS25, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 501, 64, 30));

        jLabelCreditS26.setText("2 Credits");
        add(jLabelCreditS26, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 562, 64, 30));

        jLabelCreditS27.setText("2 Credits");
        add(jLabelCreditS27, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 623, 64, 30));

        jLabelCreditS28.setText("2 Credits");
        add(jLabelCreditS28, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 684, 64, 30));

        jLabelCashS21.setText("Rs 4500");
        add(jLabelCashS21, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 259, 59, 30));

        jLabelCashS22.setText("Rs 4500");
        add(jLabelCashS22, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 319, 59, 30));

        jLabelCashS23.setText("Rs 3500");
        add(jLabelCashS23, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 379, 59, 30));

        jLabelCashS24.setText("Rs 2500");
        add(jLabelCashS24, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 440, 59, 30));

        jLabelCashS25.setText("Rs 3000");
        add(jLabelCashS25, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 501, 59, 30));

        jLabelCashS26.setText("Rs 2500");
        add(jLabelCashS26, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 562, 59, 30));

        jLabelCashS27.setText("Rs 4500");
        add(jLabelCashS27, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 623, 59, 30));

        jLabelCashS28.setText("Rs 4000");
        add(jLabelCashS28, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 684, 59, 30));

        jLabelSem1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSem1.setText("Semester 1");
        add(jLabelSem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 159, 141, 43));

        jButtonEditS2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonEditS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        jButtonEditS2.setText("Edit");
        add(jButtonEditS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 755, 148, 49));

        jButtonProceedS2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonProceedS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Proceed.png"))); // NOI18N
        jButtonProceedS2.setText("Proceed");
        add(jButtonProceedS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 755, -1, 49));
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxS18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS18ActionPerformed
        if(countSem1<=3){
            if(jCheckBoxS18.isSelected()){
                Enroll enr = new Enroll("CS1108",postg.getId(),postg.getRegDate());
                subjectsSem1[7]=enr;
            }
            countSem1++;
        }else{
            jCheckBoxS18.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxS18ActionPerformed

    private void jCheckBoxS28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS28ActionPerformed
        if(countSem2<=3){
            if(jCheckBoxS28.isSelected()){
                Enroll enr = new Enroll("CS1208",postg.getId(),postg.getRegDate());
                subjectsSem2[7]=enr;
            }
            countSem2++;
        }else{
            jCheckBoxS28.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxS28ActionPerformed

    private void jButtonProceedS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProceedS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProceedS1ActionPerformed

    private void jButtonStuIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStuIdActionPerformed
        String Id=jTextStuId.getText();
        try {
            postg = PostgraduateController.searchPostgraduate(Id);
            // object eka one wenne reg date ekata methana hoyapan sem gana
            String reg = postg.getRegDate();
            Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(reg);
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            Date date2 = new Date();
            long diff = date2.getTime() - date1.getTime();
            int days =  (int) (diff / 1000 / 60 / 60 / 24);
            if(days<180){
                
            }
            
        } catch (ClassNotFoundException | SQLException | ParseException ex) {
            Logger.getLogger(PostgraduateEvaluation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonStuIdActionPerformed

    private void jCheckBoxS13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS13ActionPerformed
        if(countSem1<=3){
            if(jCheckBoxS13.isSelected()){
                Enroll enr = new Enroll("CS1103",postg.getId(),postg.getRegDate());
                subjectsSem2[2]=enr;
            }
            countSem1++;
        }else{
            jCheckBoxS13.setEnabled(false);
        }

    }//GEN-LAST:event_jCheckBoxS13ActionPerformed

    private void jCheckBoxS14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS14ActionPerformed
        if(countSem1<=3){
            if(jCheckBoxS14.isSelected()){
                Enroll enr = new Enroll("CS1104",postg.getId(),postg.getRegDate());
                subjectsSem1[3]=enr;
            }
            countSem1++;
        }else{
            jCheckBoxS14.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxS14ActionPerformed

    private void jCheckBoxS15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS15ActionPerformed
        if(countSem1<=3){
            if(jCheckBoxS15.isSelected()){
                Enroll enr = new Enroll("CS1105",postg.getId(),postg.getRegDate());
                subjectsSem1[4]=enr;
            }
            countSem1++;
        }else{
            jCheckBoxS15.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxS15ActionPerformed

    private void jCheckBoxS16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS16ActionPerformed
        if(countSem1<=3){
            if(jCheckBoxS16.isSelected()){
                Enroll enr = new Enroll("CS1106",postg.getId(),postg.getRegDate());
                subjectsSem1[5]=enr;
            }
            countSem1++;
        }else{
            jCheckBoxS16.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxS16ActionPerformed

    private void jCheckBoxS17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS17ActionPerformed
        if(countSem1<=3){
            if(jCheckBoxS17.isSelected()){
                Enroll enr = new Enroll("CS1107",postg.getId(),postg.getRegDate());
                subjectsSem1[6]=enr;
            }
            countSem1++;
        }else{
            jCheckBoxS17.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxS17ActionPerformed

    private void jCheckBoxS23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS23ActionPerformed
        if(countSem2<=3){
            if(jCheckBoxS23.isSelected()){
                Enroll enr = new Enroll("CS1203",postg.getId(),postg.getRegDate());
                subjectsSem2[2]=enr;
            }
            countSem2++;
        }else{
            jCheckBoxS23.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxS23ActionPerformed

    private void jCheckBoxS24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS24ActionPerformed
        if(countSem2<=3){
            if(jCheckBoxS24.isSelected()){
                Enroll enr = new Enroll("CS1204",postg.getId(),postg.getRegDate());
                subjectsSem2[3]=enr;
            }
            countSem2++;
        }else{
            jCheckBoxS24.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxS24ActionPerformed

    private void jCheckBoxS25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS25ActionPerformed
        if(countSem2<=3){
            if(jCheckBoxS25.isSelected()){
                Enroll enr = new Enroll("CS1205",postg.getId(),postg.getRegDate());
                subjectsSem2[4]=enr;
            }
            countSem2++;
        }else{
            jCheckBoxS25.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxS25ActionPerformed

    private void jCheckBoxS26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS26ActionPerformed
        if(countSem2<=3){
            if(jCheckBoxS26.isSelected()){
                Enroll enr = new Enroll("CS1206",postg.getId(),postg.getRegDate());
                subjectsSem2[2]=enr;
            }
            countSem2++;
        }else{
            jCheckBoxS26.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxS26ActionPerformed

    private void jCheckBoxS27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxS27ActionPerformed
        if(countSem2<=3){
            if(jCheckBoxS27.isSelected()){
                Enroll enr = new Enroll("CS1207",postg.getId(),postg.getRegDate());
                subjectsSem2[2]=enr;
            }
            countSem2++;
        }else{
            jCheckBoxS27.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxS27ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditS1;
    private javax.swing.JButton jButtonEditS2;
    private javax.swing.JButton jButtonProceedS1;
    private javax.swing.JButton jButtonProceedS2;
    private javax.swing.JButton jButtonStuId;
    private javax.swing.JButton jButtonSubS11;
    private javax.swing.JButton jButtonSubS12;
    private javax.swing.JButton jButtonSubS21;
    private javax.swing.JButton jButtonSubS22;
    private javax.swing.JCheckBox jCheckBoxS13;
    private javax.swing.JCheckBox jCheckBoxS14;
    private javax.swing.JCheckBox jCheckBoxS15;
    private javax.swing.JCheckBox jCheckBoxS16;
    private javax.swing.JCheckBox jCheckBoxS17;
    private javax.swing.JCheckBox jCheckBoxS18;
    private javax.swing.JCheckBox jCheckBoxS23;
    private javax.swing.JCheckBox jCheckBoxS24;
    private javax.swing.JCheckBox jCheckBoxS25;
    private javax.swing.JCheckBox jCheckBoxS26;
    private javax.swing.JCheckBox jCheckBoxS27;
    private javax.swing.JCheckBox jCheckBoxS28;
    private javax.swing.JLabel jLabelCashS11;
    private javax.swing.JLabel jLabelCashS12;
    private javax.swing.JLabel jLabelCashS13;
    private javax.swing.JLabel jLabelCashS14;
    private javax.swing.JLabel jLabelCashS15;
    private javax.swing.JLabel jLabelCashS16;
    private javax.swing.JLabel jLabelCashS17;
    private javax.swing.JLabel jLabelCashS18;
    private javax.swing.JLabel jLabelCashS21;
    private javax.swing.JLabel jLabelCashS22;
    private javax.swing.JLabel jLabelCashS23;
    private javax.swing.JLabel jLabelCashS24;
    private javax.swing.JLabel jLabelCashS25;
    private javax.swing.JLabel jLabelCashS26;
    private javax.swing.JLabel jLabelCashS27;
    private javax.swing.JLabel jLabelCashS28;
    private javax.swing.JLabel jLabelCreditS11;
    private javax.swing.JLabel jLabelCreditS12;
    private javax.swing.JLabel jLabelCreditS13;
    private javax.swing.JLabel jLabelCreditS14;
    private javax.swing.JLabel jLabelCreditS15;
    private javax.swing.JLabel jLabelCreditS16;
    private javax.swing.JLabel jLabelCreditS17;
    private javax.swing.JLabel jLabelCreditS18;
    private javax.swing.JLabel jLabelCreditS21;
    private javax.swing.JLabel jLabelCreditS22;
    private javax.swing.JLabel jLabelCreditS23;
    private javax.swing.JLabel jLabelCreditS24;
    private javax.swing.JLabel jLabelCreditS25;
    private javax.swing.JLabel jLabelCreditS26;
    private javax.swing.JLabel jLabelCreditS27;
    private javax.swing.JLabel jLabelCreditS28;
    private javax.swing.JLabel jLabelSem1;
    private javax.swing.JLabel jLabelSem2;
    private javax.swing.JLabel jLabelStuId;
    private javax.swing.JTextField jTextStuId;
    // End of variables declaration//GEN-END:variables
}
