
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Instructor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bunty
 */
public class RegInstructor extends javax.swing.JPanel {

    AdminPanel adminPanel;
    String DoB;
    /**
     * Creates new form RegInstructor
     */
    public RegInstructor(AdminPanel adminPanel) {
        initComponents();
        this.adminPanel=adminPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUpdate = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabelDoB = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelContact = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jTextContact = new javax.swing.JTextField();
        jTextAddress = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jPickerDoB = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUpdate.setBackground(new java.awt.Color(0, 153, 204));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ViewPro.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 112, 244, 96));

        jButtonRegister.setBackground(new java.awt.Color(153, 153, 255));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RegisterPro.png"))); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 112, 243, 96));

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelName.setText("Name :-");
        add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 299, 178, 38));
        add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 299, 350, 38));

        jLabelDoB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDoB.setText("Date of Birth :-");
        add(jLabelDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 364, 178, 42));

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAddress.setText("Address :-");
        add(jLabelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 434, 178, 39));

        jLabelContact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelContact.setText("Contact Number :-");
        add(jLabelContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 500, 178, 43));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmail.setText("Email :-");
        add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 568, 178, 40));
        add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 570, 350, 40));
        add(jTextContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 502, 350, 43));
        add(jTextAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 435, 350, 40));

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clear.png"))); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 694, 163, 70));

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Submit.png"))); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 694, 171, 70));

        jButtonView.setBackground(new java.awt.Color(0, 153, 204));
        jButtonView.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ViewPro.png"))); // NOI18N
        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });
        add(jButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 112, 244, 96));

        jPickerDoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPickerDoBActionPerformed(evt);
            }
        });
        add(jPickerDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 140, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        RegInstructor regIns=new RegInstructor(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(regIns);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        try {
                String id=IdGenerator.getNewId("Instructor", "Instructor_Id", "IN");
                Instructor ins = new Instructor(id,jTextName.getText(),DoB,jTextAddress.getText(),jTextEmail.getText(),jTextContact.getText());
                InstructorController.addInstructor(ins);
                RegInstructor regIns=new RegInstructor(adminPanel);
                adminPanel.masterPanel.removeAll();
                adminPanel.masterPanel.add(regIns);
                adminPanel.masterPanel.repaint();
                adminPanel.masterPanel.revalidate();
                regIns.setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                System.out.println("Please Input a message box here");
                Logger.getLogger(RegLecturer.class.getName()).log(Level.SEVERE, null, ex);//how to set up jOptionPane in java
            }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        UpdateInstructor updateIns=new UpdateInstructor(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(updateIns);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        updateIns.setVisible(true);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        ViewInstructor viewIns=new ViewInstructor(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(viewIns);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        viewIns.setVisible(true);
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jPickerDoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPickerDoBActionPerformed
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        jPickerDoB.setFormats(formatter);
        DoB = formatter.format(jPickerDoB.getDate());
    }//GEN-LAST:event_jPickerDoBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelDoB;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelName;
    private org.jdesktop.swingx.JXDatePicker jPickerDoB;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextContact;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextName;
    // End of variables declaration//GEN-END:variables
}
