
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Postgraduate;


public class UpdatePostgraduate extends javax.swing.JPanel {
    AdminPanel adminPanel;
    Postgraduate postg;
    String DoB;
    /**
     * Creates new form UpdatePostgraduate
     */
    public UpdatePostgraduate(AdminPanel adminPanel) {
        this.adminPanel=adminPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabelDoB = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jTextAddress = new javax.swing.JTextField();
        jLabelContact = new javax.swing.JLabel();
        jTextContact = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabelIntake = new javax.swing.JLabel();
        jTextIntakeYear = new javax.swing.JTextField();
        jTextIntakeSem = new javax.swing.JTextField();
        jLabelQualification = new javax.swing.JLabel();
        jTextQualification = new javax.swing.JTextField();
        jLabelCompletion = new javax.swing.JLabel();
        jTextCompletion = new javax.swing.JTextField();
        jButtonSubmit = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabelFaculty = new javax.swing.JLabel();
        jTextFaculty = new javax.swing.JTextField();
        jButtonUpdate1 = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jPickerDoB = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelName.setText("Name :-");
        jPanel1.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 160, 168, 36));

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 338, 36));

        jLabelDoB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDoB.setText("Date of Birth :-");
        jPanel1.add(jLabelDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 220, 168, 36));

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAddress.setText("Address :-");
        jPanel1.add(jLabelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 280, 168, 36));
        jPanel1.add(jTextAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 338, 36));

        jLabelContact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelContact.setText("Contact Number :-");
        jPanel1.add(jLabelContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 330, -1, 36));
        jPanel1.add(jTextContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 338, 36));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmail.setText("Email :-");
        jPanel1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 380, 168, 36));
        jPanel1.add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 338, 36));

        jLabelIntake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelIntake.setText("Intake :-");
        jPanel1.add(jLabelIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 440, 168, 36));

        jTextIntakeYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIntakeYearActionPerformed(evt);
            }
        });
        jPanel1.add(jTextIntakeYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 140, 36));

        jTextIntakeSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIntakeSemActionPerformed(evt);
            }
        });
        jPanel1.add(jTextIntakeSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 140, 36));

        jLabelQualification.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQualification.setText("Qualification Type :-");
        jPanel1.add(jLabelQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 560, 192, 36));
        jPanel1.add(jTextQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 560, 338, 36));

        jLabelCompletion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCompletion.setText("Year of Completion :-");
        jPanel1.add(jLabelCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 500, -1, 36));

        jTextCompletion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCompletionActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 500, 140, 36));

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Submit.png"))); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 150, 60));

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelId.setText("Id Number >>>");
        jPanel1.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 192, 36));

        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });
        jPanel1.add(jTextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 244, 36));

        jButtonRegister.setBackground(new java.awt.Color(0, 153, 204));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RegisterPro.png"))); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 242, 97));

        jButtonView.setBackground(new java.awt.Color(0, 153, 204));
        jButtonView.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ViewPro.png"))); // NOI18N
        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 242, 97));

        jButtonUpdate.setBackground(new java.awt.Color(153, 153, 255));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UpdatePro.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 242, 97));

        jLabelFaculty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFaculty.setText("Faculty :-");
        jPanel1.add(jLabelFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 610, 192, 36));
        jPanel1.add(jTextFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 610, 338, 36));

        jButtonUpdate1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        jButtonUpdate1.setText("Update");
        jButtonUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdate1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 150, -1));

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clear.png"))); // NOI18N
        jButtonClear.setText("Delete");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 518, 150, -1));

        jPickerDoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPickerDoBActionPerformed(evt);
            }
        });
        jPanel1.add(jPickerDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIntakeYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIntakeYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIntakeYearActionPerformed

    private void jTextIntakeSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIntakeSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIntakeSemActionPerformed

    private void jTextCompletionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCompletionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCompletionActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        String id =jTextId.getText();
        try {
            postg=PostgraduateController.searchPostgraduate(id);
            jTextName.setText(postg.getName());
            jTextAddress.setText(postg.getAddress());
            jTextContact.setText(postg.getContact());
            jTextEmail.setText(postg.getEmail());
            String dateValue = postg.getDoB();
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            Date date = fmt.parse(dateValue);
            jPickerDoB.setFormats(fmt);
            jPickerDoB.setDate(date);
            String year,sem;
            String all=postg.getIntake();
            year=all.substring(0,4);
            sem=all.substring(4,all.length());
            if(sem.equals("S1")){
                jTextIntakeSem.setText("Semester 1");
            }else{
                jTextIntakeSem.setText("Semester 2");
            }
            jTextIntakeYear.setText(year);
            jTextCompletion.setText(postg.getCompletionYear());
            jTextQualification.setText(postg.getQualificationType());
            String[] Fid={"FCS01","FBS02","FES03"};
            String[] Faculty={"Computer Science","Bussiness","Engineering"};
            int j=0;
            for(int i=0;i<Fid.length;i++){
                if(Fid[i].equals(postg.getFacultyId())){
                    jTextFaculty.setText(Faculty[j]);
                    i=i+1;
                    j=j+1;
                    break;
                }
            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewPostgraduate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(UpdatePostgraduate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        RegPostgraduate regPostg=new RegPostgraduate(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(regPostg);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        regPostg.setVisible(true);

    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        ViewPostgraduate viewPostg=new ViewPostgraduate(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(viewPostg);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        viewPostg.setVisible(true);
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdate1ActionPerformed
        String id=jTextId.getText();
        String sem;
        if(jTextIntakeSem.getText().equals("Semester 1")){
            sem="S1";
        }else{
            sem="S2";
        }
        String intake=jTextIntakeYear.getText()+sem;
        String[] Fid={"FCS01","FBS02","FES03"};
        String[] Faculty={"Computer Science","Bussiness","Engineering"};
        String fid=null;
            int j=0;
            for(int i=0;i<Fid.length;i++){
                if(Faculty[i].equals(jTextFaculty.getText())){
                    fid=Fid[j];
                    i=i+1;
                    j=j+1;
                    break;
                }
            }
        Postgraduate postg1=new Postgraduate(id,jTextName.getText(),DoB,jTextAddress.getText(),jTextEmail.getText(),jTextContact.getText(),postg.getRegDate(),intake,jTextCompletion.getText(),jTextQualification.getText(),fid);
        try {
            PostgraduateController.updatePostgraduate(postg1);
            UpdatePostgraduate updatePostg=new UpdatePostgraduate(adminPanel);
            adminPanel.masterPanel.removeAll();
            adminPanel.masterPanel.add(updatePostg);
            adminPanel.masterPanel.repaint();
            adminPanel.masterPanel.revalidate();
            updatePostg.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UpdatePostgraduate.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonUpdate1ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        String id=jTextId.getText();
        UpdatePostgraduate updatePostg=new UpdatePostgraduate(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(updatePostg);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        updatePostg.setVisible(true);  
        try {
            PostgraduateController.deletePostgraduate(id);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewLecturer.class.getName()).log(Level.SEVERE, null, ex);
        }  // TODO add your ha
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jPickerDoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPickerDoBActionPerformed
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        jPickerDoB.setFormats(formatter);
        DoB = formatter.format(jPickerDoB.getDate());
    }//GEN-LAST:event_jPickerDoBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonUpdate1;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCompletion;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelDoB;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFaculty;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIntake;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelQualification;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXDatePicker jPickerDoB;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextCompletion;
    private javax.swing.JTextField jTextContact;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFaculty;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextIntakeSem;
    private javax.swing.JTextField jTextIntakeYear;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextQualification;
    // End of variables declaration//GEN-END:variables
}
