
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Stream;
import model.Undergraduate;

public class UpdateUndergraduate extends javax.swing.JPanel {
    AdminPanel adminPanel;
    Undergraduate underg;
    String DoB;
    /**
     * Creates new form UpdateUndergraduate
     */
    public UpdateUndergraduate(AdminPanel adminPanel) {
        this.adminPanel=adminPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegister = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jTextId = new javax.swing.JTextField();
        jLabelId = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jTextName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        LabelDoB = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelContact = new javax.swing.JLabel();
        jTextContact = new javax.swing.JTextField();
        jTextAddress = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jTextIntakeYear = new javax.swing.JTextField();
        jTextIntakeSem = new javax.swing.JTextField();
        jTextStream = new javax.swing.JTextField();
        jLabelStream = new javax.swing.JLabel();
        jLabelIntake = new javax.swing.JLabel();
        jLabelSubject1 = new javax.swing.JLabel();
        jTextSubject1 = new javax.swing.JTextField();
        jTextSubject2 = new javax.swing.JTextField();
        jLabelSubject2 = new javax.swing.JLabel();
        jLabelSubject3 = new javax.swing.JLabel();
        jTextSubject3 = new javax.swing.JTextField();
        jLabelEnglish = new javax.swing.JLabel();
        jTextEnglish = new javax.swing.JTextField();
        jTextRank = new javax.swing.JTextField();
        jLabelRank = new javax.swing.JLabel();
        jLabelZScore = new javax.swing.JLabel();
        jTextZScore = new javax.swing.JTextField();
        jTextFaculty = new javax.swing.JTextField();
        jLabelFaculty = new javax.swing.JLabel();
        jButtonUpdate1 = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jPickerDoB = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegister.setBackground(new java.awt.Color(0, 153, 204));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RegisterPro.png"))); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 34, -1, 96));

        jButtonView.setBackground(new java.awt.Color(0, 153, 204));
        jButtonView.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ViewPro.png"))); // NOI18N
        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });
        add(jButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 34, 243, 96));

        jButtonUpdate.setBackground(new java.awt.Color(153, 153, 255));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UpdatePro.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 34, 244, 97));

        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });
        add(jTextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 241, 244, 36));

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelId.setText("Id Number >>>");
        add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 176, 192, 36));

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Submit.png"))); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 150, 60));
        add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 178, 338, 36));

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelName.setText("Name :-");
        add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 176, 192, 36));

        LabelDoB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelDoB.setText("Date of Birth :-");
        add(LabelDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 237, 192, 36));

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAddress.setText("Address :-");
        add(jLabelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 293, 192, 36));

        jLabelContact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelContact.setText("Contact Number :-");
        add(jLabelContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 355, 192, 36));
        add(jTextContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 357, 338, 36));
        add(jTextAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 295, 338, 36));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmail.setText("Email :-");
        add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 411, 192, 36));
        add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 413, 338, 36));

        jTextIntakeYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIntakeYearActionPerformed(evt);
            }
        });
        add(jTextIntakeYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 469, 140, 36));

        jTextIntakeSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIntakeSemActionPerformed(evt);
            }
        });
        add(jTextIntakeSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 469, 140, 36));

        jTextStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextStreamActionPerformed(evt);
            }
        });
        add(jTextStream, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 530, 140, 36));

        jLabelStream.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStream.setText("Stream :-");
        add(jLabelStream, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 528, 192, 36));

        jLabelIntake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelIntake.setText("Intake :-");
        add(jLabelIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 467, 192, 36));

        jLabelSubject1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSubject1.setText("Subject 1 :-");
        add(jLabelSubject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 594, 124, 36));
        add(jTextSubject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 594, 89, 36));
        add(jTextSubject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 665, 89, 36));

        jLabelSubject2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSubject2.setText("Subject 2 :-");
        add(jLabelSubject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 663, 124, 36));

        jLabelSubject3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSubject3.setText("Subject 3 :-");
        add(jLabelSubject3, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 731, 124, 36));
        add(jTextSubject3, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 733, 89, 36));

        jLabelEnglish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEnglish.setText("English :-");
        add(jLabelEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 594, 104, 36));

        jTextEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEnglishActionPerformed(evt);
            }
        });
        add(jTextEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 594, 89, 36));

        jTextRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRankActionPerformed(evt);
            }
        });
        add(jTextRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 661, 89, 36));

        jLabelRank.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRank.setText("Rank :-");
        add(jLabelRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 663, 104, 36));

        jLabelZScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelZScore.setText("Z Score :-");
        add(jLabelZScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 731, 104, 36));
        add(jTextZScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 733, 89, 36));
        add(jTextFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 800, 338, 36));

        jLabelFaculty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFaculty.setText("Faculty :-");
        add(jLabelFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 800, 192, 36));

        jButtonUpdate1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        jButtonUpdate1.setText("Update");
        jButtonUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdate1ActionPerformed(evt);
            }
        });
        add(jButtonUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, -1, -1));

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clear.png"))); // NOI18N
        jButtonClear.setText("Delete");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 149, -1));

        jPickerDoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPickerDoBActionPerformed(evt);
            }
        });
        add(jPickerDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        RegUndergraduate regUnderg=new RegUndergraduate(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(regUnderg);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        regUnderg.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        ViewUndergraduate viewUnderg=new ViewUndergraduate(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(viewUnderg);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        viewUnderg.setVisible(true);
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        String id =jTextId.getText();
        try {
            underg=UndergraduateController.searchUndergraduate(id);
            jTextName.setText(underg.getName());
            DoB=underg.getDoB();
            String dateValue = underg.getDoB();
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            Date date = fmt.parse(dateValue);
            jPickerDoB.setFormats(fmt);
            jPickerDoB.setDate(date);
            jTextAddress.setText(underg.getAddress());
            jTextContact.setText(underg.getContact());
            jTextEmail.setText(underg.getEmail());
            String year,sem;
            String all=underg.getIntake();
            year=all.substring(0,4);
            sem=all.substring(4,all.length());
            if(sem.equals("S1")){
                jTextIntakeSem.setText("Semester 1");
            }else{
                jTextIntakeSem.setText("Semester 2");
            }
            jTextIntakeYear.setText(year);
            String[] Fid={"FCS01","FBS02","FES03"};
            String[] Faculty={"Computer Science","Bussiness","Engineering"};
            int j=0;
            for(int i=0;i<Fid.length;i++){
                if(Fid[i].equals(underg.getFaculty())){
                    jTextFaculty.setText(Faculty[j]);
                    i=i+1;
                    j=j+1;
                    break;
                }
            }
            Stream str=StreamController.searchStream(id);
            if(str.getName()=="Physical Stream"){
                jLabelSubject1.setText("Mathematics");
                jLabelSubject2.setText("Chemistry");
                jLabelSubject3.setText("Physics");
            }else if(str.getName()=="Biological Stream"){
                jLabelSubject1.setText("Biology");
                jLabelSubject2.setText("Chemistry");
                jLabelSubject3.setText("Physics");
            }else{
                jLabelSubject1.setText("Commerce");
                jLabelSubject2.setText("Econ");
                jLabelSubject3.setText("Accounting");
            }
            jTextStream.setText(str.getName());
            jTextSubject1.setText(str.getSubject1());
            jTextSubject2.setText(str.getSubject2());
            jTextSubject3.setText(str.getSubject3());
            jTextEnglish.setText(str.getEnglish());
            jTextRank.setText(str.getRank());
            jTextZScore.setText(str.getZScore());

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewPostgraduate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(UpdateUndergraduate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jTextIntakeYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIntakeYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIntakeYearActionPerformed

    private void jTextIntakeSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIntakeSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIntakeSemActionPerformed

    private void jTextStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextStreamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextStreamActionPerformed

    private void jTextEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEnglishActionPerformed

    private void jTextRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRankActionPerformed

    private void jButtonUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdate1ActionPerformed
        String id=jTextId.getText();
        String sem;
        if(jTextIntakeSem.getText().equals("Semester 1")){
            sem="S1";
        }else{
            sem="S2";
        }
        String intake=jTextIntakeYear.getText()+sem;
        String[] Fid={"FCS01","FBS02","FES03"};
        String[] Faculty={"Computer Science","Bussiness","Engineering"};
        String fid=null;
        int j=0;
        for(int i=0;i<Fid.length;i++){
            if(Faculty[i].equals(jTextFaculty.getText())){
                fid=Fid[j];
                i=i+1;
                j=j+1;
                break;
            }
        }
        String strid=null;
        if(jTextStream.equals("Physical Stream")){
            strid="CM001";
        }else if(jTextStream.equals("Biological Stream")){
            strid="BI001";
        }else{
            strid="EC001";
        }
        Undergraduate underg1=new Undergraduate(id,jTextName.getText(),DoB,jTextAddress.getText(),jTextEmail.getText(),jTextContact.getText(),underg.getRegDate(),intake,jTextStream.getText(),fid);
        Stream stream=new Stream(strid,jTextStream.getText(),jTextSubject1.getText(),jTextSubject2.getText(),jTextSubject3.getText(),jTextEnglish.getText(),jTextRank.getText(),jTextZScore.getText(),id);
        try {
            UndergraduateController.updateUndergraduate(underg1);
            StreamController.updateStream(stream);
            UpdateUndergraduate updateUnderg=new UpdateUndergraduate(adminPanel);
            adminPanel.masterPanel.removeAll();
            adminPanel.masterPanel.add(updateUnderg);
            adminPanel.masterPanel.repaint();
            adminPanel.masterPanel.revalidate();
            updateUnderg.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UpdatePostgraduate.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonUpdate1ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        String id=jTextId.getText();
        UpdatePostgraduate updatePostg=new UpdatePostgraduate(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(updatePostg);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        updatePostg.setVisible(true);
        try {
            PostgraduateController.deletePostgraduate(id);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewLecturer.class.getName()).log(Level.SEVERE, null, ex);
        }  // TODO add your ha
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jPickerDoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPickerDoBActionPerformed
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        jPickerDoB.setFormats(formatter);
        DoB = formatter.format(jPickerDoB.getDate());
    }//GEN-LAST:event_jPickerDoBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDoB;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonUpdate1;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEnglish;
    private javax.swing.JLabel jLabelFaculty;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIntake;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRank;
    private javax.swing.JLabel jLabelStream;
    private javax.swing.JLabel jLabelSubject1;
    private javax.swing.JLabel jLabelSubject2;
    private javax.swing.JLabel jLabelSubject3;
    private javax.swing.JLabel jLabelZScore;
    private org.jdesktop.swingx.JXDatePicker jPickerDoB;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextContact;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEnglish;
    private javax.swing.JTextField jTextFaculty;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextIntakeSem;
    private javax.swing.JTextField jTextIntakeYear;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextRank;
    private javax.swing.JTextField jTextStream;
    private javax.swing.JTextField jTextSubject1;
    private javax.swing.JTextField jTextSubject2;
    private javax.swing.JTextField jTextSubject3;
    private javax.swing.JTextField jTextZScore;
    // End of variables declaration//GEN-END:variables
}
