
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Stream;
import model.Undergraduate;


public class ViewUndergraduate extends javax.swing.JPanel {
    AdminPanel adminPanel;
    /**
     * Creates new form ViewUndergraduate
     */
    public ViewUndergraduate(AdminPanel adminPanel) {
        initComponents();
        this.adminPanel=adminPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        LabelDoB = new javax.swing.JLabel();
        jTextDoB = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jTextAddress = new javax.swing.JTextField();
        jLabelContact = new javax.swing.JLabel();
        jTextContact = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabelIntake = new javax.swing.JLabel();
        jLabelStream = new javax.swing.JLabel();
        jLabelZScore = new javax.swing.JLabel();
        jLabelRank = new javax.swing.JLabel();
        jLabelSubject3 = new javax.swing.JLabel();
        jLabelSubject2 = new javax.swing.JLabel();
        jLabelSubject1 = new javax.swing.JLabel();
        jTextZScore = new javax.swing.JTextField();
        jTextRank = new javax.swing.JTextField();
        jTextIntakeYear = new javax.swing.JTextField();
        jLabelEnglish = new javax.swing.JLabel();
        jTextSubject2 = new javax.swing.JTextField();
        jTextSubject1 = new javax.swing.JTextField();
        jTextSubject3 = new javax.swing.JTextField();
        StarEmail4 = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jTextEnglish = new javax.swing.JTextField();
        jTextStream = new javax.swing.JTextField();
        jTextIntakeSem = new javax.swing.JTextField();
        jButtonView = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jButtonSubmit = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabelFaculty = new javax.swing.JLabel();
        jTextFaculty = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelName.setText("Name :-");
        jPanel2.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 176, 192, 36));
        jPanel2.add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 178, 338, 36));

        LabelDoB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelDoB.setText("Date of Birth :-");
        jPanel2.add(LabelDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 237, 192, 36));
        jPanel2.add(jTextDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 239, 338, 36));

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAddress.setText("Address :-");
        jPanel2.add(jLabelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 293, 192, 36));
        jPanel2.add(jTextAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 295, 338, 36));

        jLabelContact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelContact.setText("Contact Number :-");
        jPanel2.add(jLabelContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 355, 192, 36));
        jPanel2.add(jTextContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 357, 338, 36));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmail.setText("Email :-");
        jPanel2.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 411, 192, 36));
        jPanel2.add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 413, 338, 36));

        jLabelIntake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelIntake.setText("Intake :-");
        jPanel2.add(jLabelIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 467, 192, 36));

        jLabelStream.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStream.setText("Stream :-");
        jPanel2.add(jLabelStream, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 528, 192, 36));

        jLabelZScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelZScore.setText("Z Score :-");
        jPanel2.add(jLabelZScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 731, 104, 36));

        jLabelRank.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRank.setText("Rank :-");
        jPanel2.add(jLabelRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 663, 104, 36));

        jLabelSubject3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSubject3.setText("Subject 3 :-");
        jPanel2.add(jLabelSubject3, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 731, 124, 36));

        jLabelSubject2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSubject2.setText("Subject 2 :-");
        jPanel2.add(jLabelSubject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 663, 124, 36));

        jLabelSubject1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSubject1.setText("Subject 1 :-");
        jPanel2.add(jLabelSubject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 594, 124, 36));
        jPanel2.add(jTextZScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 733, 89, 36));

        jTextRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRankActionPerformed(evt);
            }
        });
        jPanel2.add(jTextRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 661, 89, 36));

        jTextIntakeYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIntakeYearActionPerformed(evt);
            }
        });
        jPanel2.add(jTextIntakeYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 469, 140, 36));

        jLabelEnglish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEnglish.setText("English :-");
        jPanel2.add(jLabelEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 594, 104, 36));
        jPanel2.add(jTextSubject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 665, 89, 36));
        jPanel2.add(jTextSubject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 594, 89, 36));
        jPanel2.add(jTextSubject3, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 733, 89, 36));

        StarEmail4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        StarEmail4.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(StarEmail4, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 594, 19, -1));

        jButtonRegister.setBackground(new java.awt.Color(0, 153, 204));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RegisterPro.png"))); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 34, -1, 96));

        jTextEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEnglishActionPerformed(evt);
            }
        });
        jPanel2.add(jTextEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 594, 89, 36));

        jTextStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextStreamActionPerformed(evt);
            }
        });
        jPanel2.add(jTextStream, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 530, 140, 36));

        jTextIntakeSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIntakeSemActionPerformed(evt);
            }
        });
        jPanel2.add(jTextIntakeSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 469, 140, 36));

        jButtonView.setBackground(new java.awt.Color(153, 153, 255));
        jButtonView.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ViewPro.png"))); // NOI18N
        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 34, 243, 96));

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelId.setText("Id Number >>>");
        jPanel2.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 176, 192, 36));

        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });
        jPanel2.add(jTextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 241, 244, 36));

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 295, 113, 42));

        jButtonUpdate.setBackground(new java.awt.Color(0, 153, 204));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UpdatePro.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 34, 244, 97));

        jLabelFaculty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFaculty.setText("Faculty :-");
        jPanel2.add(jLabelFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 800, 192, 36));
        jPanel2.add(jTextFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 800, 338, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIntakeYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIntakeYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIntakeYearActionPerformed

    private void jTextRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRankActionPerformed

    private void jTextEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEnglishActionPerformed

    private void jTextStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextStreamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextStreamActionPerformed

    private void jTextIntakeSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIntakeSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIntakeSemActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        RegUndergraduate regUnderg=new RegUndergraduate(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(regUnderg);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        regUnderg.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        UpdateUndergraduate updateUnderg=new UpdateUndergraduate(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(updateUnderg);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        updateUnderg.setVisible(true);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        String id =jTextId.getText();
        try {
            Undergraduate underg=UndergraduateController.searchUndergraduate(id);
            jTextName.setText(underg.getName());
            jTextDoB.setText(underg.getDoB());
            jTextAddress.setText(underg.getAddress());
            jTextContact.setText(underg.getContact());
            jTextEmail.setText(underg.getEmail());
            String year,sem;
            String all=underg.getIntake();
            year=all.substring(0,4);
            sem=all.substring(4,all.length());
            if(sem.equals("S1")){
                jTextIntakeSem.setText("Semester 1");
            }else{
                jTextIntakeSem.setText("Semester 2");
            }
            jTextIntakeYear.setText(year);
            String[] Fid={"FCS01","FBS02","FES03"};
            String[] Faculty={"Computer Science","Bussiness","Engineering"};
            int j=0;
            for(int i=0;i<Fid.length;i++){
                if(Fid[i].equals(underg.getFaculty())){
                    jTextFaculty.setText(Faculty[j]);
                    i=i+1;
                    j=j+1;
                    break;
                }
            }
            Stream str=StreamController.searchStream(id);
            if(str.getName()=="Physical Stream"){
                jLabelSubject1.setText("Mathematics");
                jLabelSubject2.setText("Chemistry");
                jLabelSubject3.setText("Physics");
            }else if(str.getName()=="Biological Stream"){
                jLabelSubject1.setText("Biology");
                jLabelSubject2.setText("Chemistry");
                jLabelSubject3.setText("Physics");
            }else{
                jLabelSubject1.setText("Commerce");
                jLabelSubject2.setText("Econ");
                jLabelSubject3.setText("Accounting");
            }
            jTextStream.setText(str.getName());
            jTextSubject1.setText(str.getSubject1());
            jTextSubject2.setText(str.getSubject2());
            jTextSubject3.setText(str.getSubject3());
            jTextEnglish.setText(str.getEnglish());
            jTextRank.setText(str.getRank());
            jTextZScore.setText(str.getZScore());
            
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewPostgraduate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDoB;
    private javax.swing.JLabel StarEmail4;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEnglish;
    private javax.swing.JLabel jLabelFaculty;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIntake;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRank;
    private javax.swing.JLabel jLabelStream;
    private javax.swing.JLabel jLabelSubject1;
    private javax.swing.JLabel jLabelSubject2;
    private javax.swing.JLabel jLabelSubject3;
    private javax.swing.JLabel jLabelZScore;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextContact;
    private javax.swing.JTextField jTextDoB;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEnglish;
    private javax.swing.JTextField jTextFaculty;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextIntakeSem;
    private javax.swing.JTextField jTextIntakeYear;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextRank;
    private javax.swing.JTextField jTextStream;
    private javax.swing.JTextField jTextSubject1;
    private javax.swing.JTextField jTextSubject2;
    private javax.swing.JTextField jTextSubject3;
    private javax.swing.JTextField jTextZScore;
    // End of variables declaration//GEN-END:variables
}
