
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Postgraduate;


public class ViewPostgraduate extends javax.swing.JPanel {
    AdminPanel adminPanel;
    /**
     * Creates new form ViewPostgraduate
     * @param adminPanel
     */
    public ViewPostgraduate(AdminPanel adminPanel) {
        this.adminPanel=adminPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabelDoB = new javax.swing.JLabel();
        jTextDoB = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jTextAddress = new javax.swing.JTextField();
        jLabelContact = new javax.swing.JLabel();
        jTextContact = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabelIntake = new javax.swing.JLabel();
        jTextIntakeYear = new javax.swing.JTextField();
        jTextIntakeSem = new javax.swing.JTextField();
        jLabelQualification = new javax.swing.JLabel();
        jTextQualification = new javax.swing.JTextField();
        jLabelCompletion = new javax.swing.JLabel();
        jTextCompletion = new javax.swing.JTextField();
        jButtonSubmit = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabelFaculty = new javax.swing.JLabel();
        jTextFaculty = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelName.setText("Name :-");
        add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 244, 168, 36));
        add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 246, 338, 36));

        jLabelDoB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDoB.setText("Date of Birth :-");
        add(jLabelDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 305, 168, 36));
        add(jTextDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 307, 338, 36));

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAddress.setText("Address :-");
        add(jLabelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 361, 168, 36));
        add(jTextAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 363, 338, 36));

        jLabelContact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelContact.setText("Contact Number :-");
        add(jLabelContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 417, -1, 36));
        add(jTextContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 419, 338, 36));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmail.setText("Email :-");
        add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 473, 168, 36));
        add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 475, 338, 36));

        jLabelIntake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelIntake.setText("Intake :-");
        add(jLabelIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 529, 168, 36));

        jTextIntakeYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIntakeYearActionPerformed(evt);
            }
        });
        add(jTextIntakeYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 531, 140, 36));

        jTextIntakeSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIntakeSemActionPerformed(evt);
            }
        });
        add(jTextIntakeSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 531, 140, 36));

        jLabelQualification.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQualification.setText("Qualification Type :-");
        add(jLabelQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 646, 192, 36));
        add(jTextQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 648, 338, 36));

        jLabelCompletion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCompletion.setText("Year of Completion :-");
        add(jLabelCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 590, -1, 36));

        jTextCompletion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCompletionActionPerformed(evt);
            }
        });
        add(jTextCompletion, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 592, 140, 36));

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 113, 42));

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelId.setText("Id Number >>>");
        add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 192, 36));

        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });
        add(jTextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 244, 36));

        jButtonRegister.setBackground(new java.awt.Color(0, 153, 204));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RegisterPro.png"))); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 242, 97));

        jButtonView.setBackground(new java.awt.Color(153, 153, 255));
        jButtonView.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ViewPro.png"))); // NOI18N
        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });
        add(jButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 242, 97));

        jButtonUpdate.setBackground(new java.awt.Color(0, 153, 204));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UpdatePro.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 242, 97));

        jLabelFaculty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFaculty.setText("Faculty :-");
        add(jLabelFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 702, 192, 36));
        add(jTextFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 704, 338, 36));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIntakeYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIntakeYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIntakeYearActionPerformed

    private void jTextIntakeSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIntakeSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIntakeSemActionPerformed

    private void jTextCompletionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCompletionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCompletionActionPerformed

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        RegPostgraduate regPostg=new RegPostgraduate(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(regPostg);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        regPostg.setVisible(true);
        
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed

    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        UpdatePostgraduate updatePostg=new UpdatePostgraduate(adminPanel);
        adminPanel.masterPanel.removeAll();
        adminPanel.masterPanel.add(updatePostg);
        adminPanel.masterPanel.repaint();
        adminPanel.masterPanel.revalidate();
        updatePostg.setVisible(true);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        String id =jTextId.getText();
        try {
            Postgraduate postg=PostgraduateController.searchPostgraduate(id);
            if(postg==null){
                JOptionPane.showMessageDialog(adminPanel, "Not a Registered Lecturer");
            }
            jTextName.setText(postg.getName());
            jTextDoB.setText(postg.getDoB());
            jTextAddress.setText(postg.getAddress());
            jTextContact.setText(postg.getContact());
            jTextEmail.setText(postg.getEmail());
            String year,sem;
            String all=postg.getIntake();
            year=all.substring(0,4);
            sem=all.substring(4,all.length());
            System.out.println(sem);
            if(sem.equals("S1")){
                jTextIntakeSem.setText("Semester 1");
            }else{
                jTextIntakeSem.setText("Semester 2");
            }
            jTextIntakeYear.setText(year);
            jTextCompletion.setText(postg.getCompletionYear());
            jTextQualification.setText(postg.getQualificationType());
            String[] Fid={"FCS01","FBS02","FES03"};
            String[] Faculty={"Computer Science","Bussiness","Engineering"};
            int j=0;
            for(int i=0;i<Fid.length;i++){
                if(Fid[i].equals(postg.getFaculty())){
                    jTextFaculty.setText(Faculty[j]);
                    i=i+1;
                    j=j+1;
                    break;
                }
            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            ExceptionHandle.showError(ex);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCompletion;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelDoB;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFaculty;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIntake;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelQualification;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextCompletion;
    private javax.swing.JTextField jTextContact;
    private javax.swing.JTextField jTextDoB;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFaculty;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextIntakeSem;
    private javax.swing.JTextField jTextIntakeYear;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextQualification;
    // End of variables declaration//GEN-END:variables
}
